version: '3'

services:
  monerod:
    container_name: monerod
    image: sethsimmons/simple-monerod:latest
    restart: always
    volumes:
      - /Users/service/monerod/lmdb:/home/monero/.bitmonero/lmdb
    ports:
      - "18080:18080"
      - "18089:18089"
      - "18084:18084"
    command:
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --rpc-bind-ip=0.0.0.0
      - --rpc-bind-port=18081
      - --confirm-external-bind
      - --check-updates=disabled
      - --max-log-files=3
      - --max-log-file-size=1048576
      - --no-igd
      - --out-peers=64
      - --limit-rate-down=1048576
      - --prune-blockchain
      - --public-node
      - --zmq-pub=tcp://0.0.0.0:18084
      - --log-level=1
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:18081/get_height || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
